version: '3'

services:
  some-scylla:
    image: scylladb/scylla
    container_name: some-scylla
    ports:
      - 9001:9042

  some-scylla2:
    image: scylladb/scylla
    container_name: some-scylla2
    command: --seeds=some-scylla
    ports:
      - 9002:9042

  some-scylla3:
    image: scylladb/scylla
    container_name: some-scylla3
    command: --seeds=some-scylla
    ports:
      - 9003:9042