version: '2'

# 3 node cluster
# If you see exit code 137 (OOM killer) then ensure Docker has access to more resources
services:
  cassandra-seed:
    container_name: cassandra-seed-node
    image: cassandra:3.11.0
    ports:
      - "9001:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"

  cassandra-node-1:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    depends_on:
      - "cassandra-seed"
    ports:
      - "9002:9042"

  # you cannot have multiple nodes join the cluster at the same time when
  # cassandra.consistent.rangemovement is true so we further delay it to give it time to stabilize
  cassandra-node-2:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    depends_on:
      - "cassandra-seed"
    ports:
      - "9003:9042"

  cassandra-node-3:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 120 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    depends_on:
      - "cassandra-seed"
    ports:
      - "9004:9042"


  cassandra-node-4:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 170 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    depends_on:
      - "cassandra-seed"
    ports:
      - "9005:9042"